### ISSUE TITLE
DM Owner crashing the bot

### ISSUE THREAD

**Issue by SriHari-15** [TechVevo/Server-Nuker#1]
**Describe the bug**
When using `.dmowner <count>` and the Owner's DMs are disabled, the bot crashes

**To Reproduce**
1. Create a temp server and add the bot
2. Change your Privacy Settings for that temp server and disable DMs
3. Now start the bot and run `.dmowner 3`

**Expected behavior**
When DMs are disabled, should throw an error in the console (or) in the channel

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - Browser: Chrome

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by TechVevo** [comment]
Thanks for bringing this to my notice. I've added `.catch()` to all the DM commands including but not limited to `dmowner` and it will be commited to the `master` branch soon. Check back in a few minutes to fix the issue.

-------------------
- Issue fixed and commited to the `master` branch
