### ISSUE TITLE
Check for updates

### ISSUE THREAD

**Issue by SriHari-15** [TechVevo/Server-Nuker#2]
**Is your feature request related to a problem? Please describe.**
Really frustrating when I stumble upon the releases and find out that I was using an outdated version

**Describe the solution you'd like**
It would be more easy to use if the EXE could inform us when a new update is available in the git.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by TechVevo** [comment]
Thanks for your suggestion. I will look into this and respond as soon as I get a clear idea/response

**Comment by TechVevo** [comment]
Successfully added! Thanks for your suggestion
